[build]
  builder = "nixpacks"
  buildCommand = "cd server && npm install --legacy-peer-deps && npm run build"
  startCommand = "npm start"
  base = "server"

[deploy]
  target = "nodejs"
  nodeVersion = "18"

[build.environment]
  NODE_ENV = "production"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[build.extraPackages]
  system = ["python3"]  # Required for some node-gyp builds

# Uncomment and configure if you need to run database migrations
# [deploy.start]
#   command = "npm run db:push && npm start"
#   wait = 30  # Wait 30 seconds for the database to be ready
